# Generated by Django 4.1.1 on 2022-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0002_estudios_experiencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='numeroDocumento',
            field=models.FloatField(),
        ),
    ]
