# Generated by Django 4.1.1 on 2022-09-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0003_alter_empleados_numerodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='idEstudios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appDjango.estudios'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='idExperiencias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appDjango.experiencias'),
        ),
    ]
